export const SECOND_LINE_OPTIONS: string[] = [
  "Unlock Knowledge",
  "Turn Notes into Talk",
  "Questions, Meet Answers",
  "Insights, Instant & Clear",
  "Textbooks as Study Partners",
  "Simply Study, Simply Succeed",
  "Bring Your Notes Alive",
  "Interactive Pages Await",
  "Learn Smarter, Not Harder",
  "Empower Your Journey",
  "Curiosity Gets Answers",
  "Master Topics with Ease",
  "Accelerate Your Growth",
  "Dive Deep, Learn Fast",
  "Make Study Time Count",
  "Study & Succeed Confidently",
  "Your Seamless Learning Hub",
  "Power Up Understanding",
  "Navigate Complex Ideas",
  "Learning's Future Starts Here",
];
